package dev.hbm.qris_testingtools.Enum;

public enum FunctionSrcEnum {
    DEFAULT,
    INPUT,
    CURRENT_QUERY_PARAM,
    CURRENT_REQUEST_HEADER,
    CURRENT_REQUEST_BODY,
    CURRENT_RESPONSE_HEADER,
    CURRENT_RESPONSE_BODY,
    PREVIOUS_QUERY_PARAM,
    PREVIOUS_REQUEST_HEADER,
    PREVIOUS_REQUEST_BODY,
    PREVIOUS_RESPONSE_HEADER,
    PREVIOUS_RESPONSE_BODY,
    SECURITY_CONFIG,
    INT_FUNCTION,
    ADDT_DATA
}
